baseURL: "https://coreyaustin.github.io/"
title: "Corey Austin's Website"
languageCode: "en"
theme: "PaperModX"

enableInlineShortcodes: true
enableRobotsTXT: true

pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Papers
      url: papers/
      weight: 2
    - name: Courses
      url: courses/
      weight: 3
    # - name: Data
    #   url: data/
    #   weight: 4

params:
  description: "This website hosts Corey Austin's research papers, course materials, data, curriculum vitae, and contact information."
  author: "Corey Austin"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["courses", "papers"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  TocSide: "left"

  profileMode:
    enabled: true
    title: "Professor Corey Austin"
    subtitle: "I am a researcher at Brookhaven National Laboratory and a Professor in the Physics Department at Hofstra University. My research focuses on optical metrology for synchrotron x-ray mirrors."
    imageUrl: "picture.jpeg"
    imageWidth: 60
    imageHeight: 60
    buttons:
      - name: Papers
        url: papers/
      # - name: Data
      #   url: data/
      - name: Courses
        url: courses/
      - name: Tags
        url: tags/
      - name: Archive
        url: archive/

  socialIcons:
    - name: Email
      url: "mailto:corey@austinphysics.com"
      title: "Email me"
    - name: linkedin
      url: "https://www.linkedin.com/in/coreyaustin/"
      title: "LinkedIn profile"
    - name: github
      url: "https://github.com/coreyaustin"
      title: "GitHub profile"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=QDtJbIMAAAAJ&hl=en"
      title: "Google Scholar profile"
    - name: orcid
      url: "https://orcid.org/0000-0001-5488-9480"
      title: "ORCID profile"
    - name: cv
      url: "cv.pdf"
      title: "Curriculum Vitae (CV)"

  assets:
    disableScrollBarStyle: true
    disableHLJS: false          # disable highlight.js (false = keep it)
    disableFingerprinting: true # avoids cache-busting hashes
    css: []                     # required for PaperModX
    js: []                      # required for PaperModX

  cover:
    hiddenInList: false
    hiddenInSingle: true

  label:
    text: "Corey Austin"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
